routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//SERVE AS PÁGINAS EM RESPOSTA A REQUISIÇÕES
Route::get('/', [\App\Http\Controllers\PrincipalController::class, 'principal'])
     ->name('site.index')
     ->middleware('log.acesso');

Route::get('/sobrenos', [\App\Http\Controllers\SobreNosController::class, 'principal'])
     ->name('site.sobrenos')
     ->middleware('log.acesso');

Route::get('/contato', [\App\Http\Controllers\ContatoController::class, 'principal'])
     ->name('site.contato');

Route::post('/contato', [\App\Http\Controllers\ContatoController::class, 'salvar'])->name('site.contato');

Route::get('/login/{erro?}', [\App\Http\Controllers\LoginController::class, 'principal'])->name('site.login');
Route::post('/login', [\App\Http\Controllers\LoginController::class, 'autenticar'])->name('site.login');

/**
 * As rotas abaixo da 'prefix' serão acessadas apenas com o /app precedendo a URI
 */
Route::middleware('autenticacao:padrao,visitante')->prefix('/app')->group(function() {
     Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])
          ->name('app.home');

     Route::get('/sair', [\App\Http\Controllers\LoginController::class, 'sair'])
          ->name('app.sair');

     Route::get('/fornecedor', [\App\Http\Controllers\FornecedorController::class, 'index'])
          ->name('app.fornecedor');

     Route::post('/fornecedor/listar', [\App\Http\Controllers\FornecedorController::class, 'listar'])
          ->name('app.fornecedor.listar');

     Route::get('/fornecedor/listar', [\App\Http\Controllers\FornecedorController::class, 'listar'])
          ->name('app.fornecedor.listar');

     Route::get('/fornecedor/adicionar', [\App\Http\Controllers\FornecedorController::class, 'adicionar'])
          ->name('app.fornecedor.adicionar');

     Route::post('/fornecedor/adicionar', [\App\Http\Controllers\FornecedorController::class, 'adicionar'])
          ->name('app.fornecedor.adicionar');

     Route::get('/fornecedor/editar/{id}/{msg?}', [\App\Http\Controllers\FornecedorController::class, 'editar'])
          ->name('app.fornecedor.editar');

     Route::get('/fornecedor/excluir/{id}', [\App\Http\Controllers\FornecedorController::class, 'excluir'])
          ->name('app.fornecedor.excluir');

     Route::get('/produto', [\App\Http\Controllers\ProdutoController::class, 'index'])
          ->name('app.produto');

     Route::resource('produto', \App\Http\Controllers\ProdutoController::class);
     Route::resource('produto-detalhe', \App\Http\Controllers\ProdutoDetalheController::class);
     Route::resource('cliente', \App\Http\Controllers\ClienteController::class);
     Route::resource('pedido', \App\Http\Controllers\PedidoController::class);

     Route::get('pedido-produto/create/{pedido}', [\App\Http\Controllers\PedidoProdutoController::class, 'create'])->name('pedido-produto.create');
     Route::post('pedido-produto/store/{pedido}', [\App\Http\Controllers\PedidoProdutoController::class, 'store'])->name('pedido-produto.store');
     Route::delete('pedido-produto/destroy/{pedidoProduto}/{pedidoId}', [\App\Http\Controllers\PedidoProdutoController::class, 'destroy'])->name('pedido-produto.destroy');
});



/**
 * {}  indica parâmetros que serão substituídos pelos nomes definidos no caminho da URL
 * {?} indica que o parâmetro é opcional
 */
Route::get(
    '/contato/{nome}/{categoriaId}', 
    function (
        string $nome = 'Desconhecido',
        int $categoriaId = 1
    ) {
        echo "Estamos aqui: " . $nome . " - " . $categoriaId;
    }

    //PROCESSA A ROTA APENAS CASO SEJA UM NÚMERO
)->where('categoriaId', '[0-9]+')
 ->where('nome', '[A-Za-z]+');


Route::get('/teste/{p1}/{p2}', [\App\Http\Controllers\TesteController::class, 'teste'])->name('teste');


// --------------- REDIRECT ---------------- //
Route::get('/rota1', function() {
     return "Rota 1"; 
})->name('site.rota1');


/**
 * DUAS MANEIRAS DE REALIZAR REDIRECTS
 */
//Route::redirect('/rota2', '/rota1');
Route::get('/rota2', function() {
     return redirect()->route('site.rota1');
})->name('site.rota2');


Route::fallback(function() {
    echo 'A rota acessada não existe, <a href="'.route('site.index').'"> clique aqui </a>para ir para página inicial!';
});

/** verbo HTTP
 * 
 * GET
 * POST
 * PUT
 * PATCH
 * DELETE
 * OPTIONS
 */

app/Models/Pedido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pedido extends Model
{
    use HasFactory;

    public function produtos() {
        //withPivot() retorna os dados da tabela produto_pedido, não apenas as chaves estrangeiras
        return $this->belongsToMany('App\Models\Item', 'pedido_produtos', 'pedido_id', 'produto_id')->withPivot('id', 'created_at');

        /**
         * 1 - Modelo do relacionamento em relação ao Modelo que estamos implementando
         * 2 - É  tabela que armazena os registros do relacionamento
         * 3 - Representa o nome da FK da tabela mapeada pelo modelo da tabela de relacionamento
         * 4 - Representa o nome da FK da tabela mapeamento pelo model utilizado no relacionamento que estamos implementando
         */
    }
}

app/Http/Controllers/PedidoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cliente;
use App\Models\Pedido;
use Illuminate\Http\Request;

class PedidoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pedidos = Pedido::paginate(10);

        return view('app.pedido.index', ['pedidos' => $pedidos, 'request' => $request->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clientes = Cliente::all();

        return view('app.pedido.create', ['clientes' => $clientes]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $regras = [
            'cliente_id' => 'exists:clientes,id'
        ];

        $feedback = [
            'cliente_id.exists' => 'O cliente informado não existe'
        ];

        $request->validate($regras, $feedback);

        $pedido = new Pedido();

        $pedido->cliente_id = $request->get('cliente_id');
        $pedido->save();

        return redirect()->route('pedido.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app/pedido/create.blade.php
@extends('app.layouts.basico')

@section('titulo', 'Pedido Produto')
{{-- DETERMINA QUAL O TRECHO DE HTML QUE OCUPARÁ A VARIÁVEL DE CONTEÚDO --}}
@section('conteudo')
    
<div class="conteudo-pagina">

    <div class="titulo-pagina-2">
        <p>Adicionar Pedido</p>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('pedido.index') }}">Voltar</a></li>
            <li><a href="">Consulta</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">
        <div class="" style="width: 30%; margin-left: auto; margin-right: auto;">
            @component('app.pedido._components.form_create_edit', ['clientes' => $clientes])
            @endcomponent
        </div>
    </div>

</div>

@endsection

resources/views/app/pedido/index.blade.php
@extends('app.layouts.basico')

@section('titulo', 'Pedidos')
{{-- DETERMINA QUAL O TRECHO DE HTML QUE OCUPARÁ A VARIÁVEL DE CONTEÚDO --}}
@section('conteudo')
    
<div class="conteudo-pagina">

    <div class="titulo-pagina-2">
        <p>Listagem de Pedidos</p>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('pedido.create') }}">Novo</a></li>
            <li><a href="">Consulta</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">
        <div class="" style="width: 90%; margin-left: auto; margin-right: auto;">
            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>ID Pedido</th>
                        <th>Cliente</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($pedidos as $pedido)
                        <tr>
                            <td>{{ $pedido->id }}</td>
                            <td>{{ $pedido->cliente_id }}</td>
                            <td><a href="{{ route('pedido-produto.create', ['pedido' => $pedido->id]) }}">Adicionar Produtos</a></td>
                            <td><a href="{{ route('pedido.show', ['pedido' => $pedido->id]) }}">Visualizar</a></td>
                            <td>
                                <form id="form_{{$pedido->id}}" method="post" action="{{ route('pedido.destroy', ['pedido' => $pedido->id]) }}">
                                    @method('DELETE')
                                    @csrf
                                    {{-- <button type="submit">Excluir</button> --}}
                                    <a href="#" onclick="document.getElementById('form_{{$pedido->id}}').submit()">Excluir</a>
                                </form>
                            </td>
                            <td><a href="{{ route('pedido.edit', ['pedido' => $pedido->id]) }}">Editar</a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $pedidos->appends($request)->links() }}
            <br>
            {{ $pedidos->count() }} - pedidos por página
            <br>
            {{ $pedidos->total() }} - Total de registros da consulta   
            <br>
            {{ $pedidos->firstItem() }} - Número do primeiro registro da página      
            <br>
            Exibindo {{ $pedidos->count() }} pedidos de {{ $pedidos->total() }} (de {{ $pedidos->firstItem() }} a {{ $pedidos->lastItem() }})
    </div>

</div>

@endsection