routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//SERVE AS PÁGINAS EM RESPOSTA A REQUISIÇÕES
Route::get('/', [\App\Http\Controllers\PrincipalController::class, 'principal'])
     ->name('site.index')
     ->middleware('log.acesso');

Route::get('/sobrenos', [\App\Http\Controllers\SobreNosController::class, 'principal'])
     ->name('site.sobrenos')
     ->middleware('log.acesso');

Route::get('/contato', [\App\Http\Controllers\ContatoController::class, 'principal'])
     ->name('site.contato');

Route::post('/contato', [\App\Http\Controllers\ContatoController::class, 'salvar'])->name('site.contato');

Route::get('/login/{erro?}', [\App\Http\Controllers\LoginController::class, 'principal'])->name('site.login');
Route::post('/login', [\App\Http\Controllers\LoginController::class, 'autenticar'])->name('site.login');

/**
 * As rotas abaixo da 'prefix' serão acessadas apenas com o /app precedendo a URI
 */
Route::middleware('autenticacao:padrao,visitante')->prefix('/app')->group(function() {
     Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])
          ->name('app.home');

     Route::get('/sair', [\App\Http\Controllers\LoginController::class, 'sair'])
          ->name('app.sair');

     Route::get('/fornecedor', [\App\Http\Controllers\FornecedorController::class, 'index'])
          ->name('app.fornecedor');

     Route::post('/fornecedor/listar', [\App\Http\Controllers\FornecedorController::class, 'listar'])
          ->name('app.fornecedor.listar');

     Route::get('/fornecedor/listar', [\App\Http\Controllers\FornecedorController::class, 'listar'])
          ->name('app.fornecedor.listar');

     Route::get('/fornecedor/adicionar', [\App\Http\Controllers\FornecedorController::class, 'adicionar'])
          ->name('app.fornecedor.adicionar');

     Route::post('/fornecedor/adicionar', [\App\Http\Controllers\FornecedorController::class, 'adicionar'])
          ->name('app.fornecedor.adicionar');

     Route::get('/fornecedor/editar/{id}/{msg?}', [\App\Http\Controllers\FornecedorController::class, 'editar'])
          ->name('app.fornecedor.editar');

     Route::get('/fornecedor/excluir/{id}', [\App\Http\Controllers\FornecedorController::class, 'excluir'])
          ->name('app.fornecedor.excluir');

     Route::get('/produto', [\App\Http\Controllers\ProdutoController::class, 'index'])
          ->name('app.produto');

     Route::resource('produto', \App\Http\Controllers\ProdutoController::class);
     Route::resource('produto-detalhe', \App\Http\Controllers\ProdutoDetalheController::class);
     Route::resource('cliente', \App\Http\Controllers\ClienteController::class);
     Route::resource('pedido', \App\Http\Controllers\PedidoController::class);

     Route::get('pedido-produto/create/{pedido}', [\App\Http\Controllers\PedidoProdutoController::class, 'create'])->name('pedido-produto.create');
     Route::post('pedido-produto/store/{pedido}', [\App\Http\Controllers\PedidoProdutoController::class, 'store'])->name('pedido-produto.store');
     Route::delete('pedido-produto/destroy/{pedidoProduto}/{pedidoId}', [\App\Http\Controllers\PedidoProdutoController::class, 'destroy'])->name('pedido-produto.destroy');
});



/**
 * {}  indica parâmetros que serão substituídos pelos nomes definidos no caminho da URL
 * {?} indica que o parâmetro é opcional
 */
Route::get(
    '/contato/{nome}/{categoriaId}', 
    function (
        string $nome = 'Desconhecido',
        int $categoriaId = 1
    ) {
        echo "Estamos aqui: " . $nome . " - " . $categoriaId;
    }

    //PROCESSA A ROTA APENAS CASO SEJA UM NÚMERO
)->where('categoriaId', '[0-9]+')
 ->where('nome', '[A-Za-z]+');


Route::get('/teste/{p1}/{p2}', [\App\Http\Controllers\TesteController::class, 'teste'])->name('teste');


// --------------- REDIRECT ---------------- //
Route::get('/rota1', function() {
     return "Rota 1"; 
})->name('site.rota1');


/**
 * DUAS MANEIRAS DE REALIZAR REDIRECTS
 */
//Route::redirect('/rota2', '/rota1');
Route::get('/rota2', function() {
     return redirect()->route('site.rota1');
})->name('site.rota2');


Route::fallback(function() {
    echo 'A rota acessada não existe, <a href="'.route('site.index').'"> clique aqui </a>para ir para página inicial!';
});

/** verbo HTTP
 * 
 * GET
 * POST
 * PUT
 * PATCH
 * DELETE
 * OPTIONS
 */

app/Models/PedidoProduto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PedidoProduto extends Model
{
    use HasFactory;
}

app/Http/Controllers/PedidoProdutoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pedido;
use App\Models\PedidoProduto;
use App\Models\Produto;
use Illuminate\Http\Request;

use function Psy\debug;

class PedidoProdutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Pedido $pedido)
    {
        $produtos = Produto::all();
        //$pedido->produtos; // força o carregamento EAGER LOADING

        return view('app.pedido_produto.create', ['pedido' => $pedido, 'produtos' => $produtos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Pedido $pedido)
    {
        $regras = [
            'produto_id' => 'exists:produtos,id',
            'quantidade' => 'required'
        ];

        $feedback = [
            'produto_id.exists' => 'O produto informado não existe',
            'required'          => 'O campo :attribute deve possuir um valor válido'
        ];

        $request->validate($regras, $feedback);

        /*$pedidoProduto = new PedidoProduto();
        $pedidoProduto->pedido_id  = $pedido->id;
        $pedidoProduto->produto_id = $request->get('produto_id');
        $pedidoProduto->quantidade = $request->get('quantidade');
        $pedidoProduto->save();*/

        //grava associações de relacionamento no banco de dados
        $pedido->produtos()->attach($request->get('produto_id'), [
            'quantidade' => $request->get('quantidade')
        ]);

        return redirect()->route('pedido-produto.create', ['pedido' => $pedido->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(PedidoProduto $pedidoProduto, $pedidoId)
    {
        // PedidoProduto::where([
        //     'pedido_id'  => $pedido->id,
        //     'produto_id' => $produto->id
        // ])->delete();
        $pedidoProduto->delete();

        return redirect()->route('pedido-produto.create', ['pedido' => $pedidoId]);
    }
}

resources/views/app/pedido_produto/create.blade.php
@extends('app.layouts.basico')

@section('titulo', 'Pedido Produto')
{{-- DETERMINA QUAL O TRECHO DE HTML QUE OCUPARÁ A VARIÁVEL DE CONTEÚDO --}}
@section('conteudo')
    
<div class="conteudo-pagina">

    <div class="titulo-pagina-2">
        <p>Adicionar Produtos ao Pedido</p>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('pedido.index') }}">Voltar</a></li>
            <li><a href="">Consulta</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">
        <h4>Detalhes do Pedido</h4>
        <p>ID do Pedido: {{ $pedido->id }}</p>
        <p>Cliente: {{ $pedido->cliente_id }}</p>

        <div class="" style="width: 30%; margin-left: auto; margin-right: auto;">
            <h1>Itens do pedido</h1>
            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome do Produto</th>
                        <th>Data de inclusão do Item no pedido</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($pedido->produtos as $produto)
                        <tr>
                            <td>{{ $produto->id }}</td>
                            <td>{{ $produto->nome }} </td>
                            <td>{{ $produto->pivot->created_at->format('d/m/Y') }} </td>
                            <td>
                                <form id="form_{{$produto->pivot->id}}" method="post" action="{{route('pedido-produto.destroy', ['pedidoProduto' => $produto->pivot->id, 'pedidoId' => $pedido->id])}}">
                                    @method('DELETE')
                                    @csrf
                                    <a href="#" onclick="document.getElementById('form_{{$produto->pivot->id}}').submit()">Excluir</a>                                
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            @component('app.pedido_produto._components.form_create', ['pedido' => $pedido, 'produtos' => $produtos])
                
            @endcomponent
        </div>
    </div>

</div>

@endsection