routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//SERVE AS PÁGINAS EM RESPOSTA A REQUISIÇÕES
Route::get('/', [\App\Http\Controllers\PrincipalController::class, 'principal'])
     ->name('site.index')
     ->middleware('log.acesso');

Route::get('/sobrenos', [\App\Http\Controllers\SobreNosController::class, 'principal'])
     ->name('site.sobrenos')
     ->middleware('log.acesso');

Route::get('/contato', [\App\Http\Controllers\ContatoController::class, 'principal'])
     ->name('site.contato');

Route::post('/contato', [\App\Http\Controllers\ContatoController::class, 'salvar'])->name('site.contato');

Route::get('/login/{erro?}', [\App\Http\Controllers\LoginController::class, 'principal'])->name('site.login');
Route::post('/login', [\App\Http\Controllers\LoginController::class, 'autenticar'])->name('site.login');

/**
 * As rotas abaixo da 'prefix' serão acessadas apenas com o /app precedendo a URI
 */
Route::middleware('autenticacao:padrao,visitante')->prefix('/app')->group(function() {
     Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])
          ->name('app.home');

     Route::get('/sair', [\App\Http\Controllers\LoginController::class, 'sair'])
          ->name('app.sair');

     Route::get('/fornecedor', [\App\Http\Controllers\FornecedorController::class, 'index'])
          ->name('app.fornecedor');

     Route::post('/fornecedor/listar', [\App\Http\Controllers\FornecedorController::class, 'listar'])
          ->name('app.fornecedor.listar');

     Route::get('/fornecedor/listar', [\App\Http\Controllers\FornecedorController::class, 'listar'])
          ->name('app.fornecedor.listar');

     Route::get('/fornecedor/adicionar', [\App\Http\Controllers\FornecedorController::class, 'adicionar'])
          ->name('app.fornecedor.adicionar');

     Route::post('/fornecedor/adicionar', [\App\Http\Controllers\FornecedorController::class, 'adicionar'])
          ->name('app.fornecedor.adicionar');

     Route::get('/fornecedor/editar/{id}/{msg?}', [\App\Http\Controllers\FornecedorController::class, 'editar'])
          ->name('app.fornecedor.editar');

     Route::get('/fornecedor/excluir/{id}', [\App\Http\Controllers\FornecedorController::class, 'excluir'])
          ->name('app.fornecedor.excluir');

     Route::get('/produto', [\App\Http\Controllers\ProdutoController::class, 'index'])
          ->name('app.produto');

     Route::resource('produto', \App\Http\Controllers\ProdutoController::class);
     Route::resource('produto-detalhe', \App\Http\Controllers\ProdutoDetalheController::class);
     Route::resource('cliente', \App\Http\Controllers\ClienteController::class);
     Route::resource('pedido', \App\Http\Controllers\PedidoController::class);

     Route::get('pedido-produto/create/{pedido}', [\App\Http\Controllers\PedidoProdutoController::class, 'create'])->name('pedido-produto.create');
     Route::post('pedido-produto/store/{pedido}', [\App\Http\Controllers\PedidoProdutoController::class, 'store'])->name('pedido-produto.store');
     Route::delete('pedido-produto/destroy/{pedidoProduto}/{pedidoId}', [\App\Http\Controllers\PedidoProdutoController::class, 'destroy'])->name('pedido-produto.destroy');
});



/**
 * {}  indica parâmetros que serão substituídos pelos nomes definidos no caminho da URL
 * {?} indica que o parâmetro é opcional
 */
Route::get(
    '/contato/{nome}/{categoriaId}', 
    function (
        string $nome = 'Desconhecido',
        int $categoriaId = 1
    ) {
        echo "Estamos aqui: " . $nome . " - " . $categoriaId;
    }

    //PROCESSA A ROTA APENAS CASO SEJA UM NÚMERO
)->where('categoriaId', '[0-9]+')
 ->where('nome', '[A-Za-z]+');


Route::get('/teste/{p1}/{p2}', [\App\Http\Controllers\TesteController::class, 'teste'])->name('teste');


// --------------- REDIRECT ---------------- //
Route::get('/rota1', function() {
     return "Rota 1"; 
})->name('site.rota1');


/**
 * DUAS MANEIRAS DE REALIZAR REDIRECTS
 */
//Route::redirect('/rota2', '/rota1');
Route::get('/rota2', function() {
     return redirect()->route('site.rota1');
})->name('site.rota2');


Route::fallback(function() {
    echo 'A rota acessada não existe, <a href="'.route('site.index').'"> clique aqui </a>para ir para página inicial!';
});

/** verbo HTTP
 * 
 * GET
 * POST
 * PUT
 * PATCH
 * DELETE
 * OPTIONS
 */

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cliente;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clientes = Cliente::paginate(10);

        return view('app.cliente.index', ['clientes' => $clientes, 'request' => $request->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('app.cliente.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $regras = [
            'nome' => 'required|min:3|max:40'
        ];

        $feedback = [
            'required' => 'O campo :attribute deve ser preenchido',
            'nome.min' => 'O campo "nome" deve ter no mínimo 3 caracteres',
            'nome.max' => 'O campo nome deve ter no máximo 40 caracteres'
        ];

        $request->validate($regras, $feedback);

        $cliente = new Cliente();

        $cliente->nome = $request->get('nome');
        $cliente->save();

        return redirect()->route('cliente.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app/cliente/create.blade.php
@extends('app.layouts.basico')

@section('titulo', 'Fornecedor')
{{-- DETERMINA QUAL O TRECHO DE HTML QUE OCUPARÁ A VARIÁVEL DE CONTEÚDO --}}
@section('conteudo')
    
<div class="conteudo-pagina">

    <div class="titulo-pagina-2">
        <p>Adicionar Cliente</p>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('cliente.index') }}">Voltar</a></li>
            <li><a href="">Consulta</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">
        <div class="" style="width: 30%; margin-left: auto; margin-right: auto;">
            @component('app.cliente._components.form_create_edit')
            @endcomponent
        </div>
    </div>

</div>

@endsection

resources/views/app/cliente/index.blade.php
@extends('app.layouts.basico')

@section('titulo', 'Cliente')
{{-- DETERMINA QUAL O TRECHO DE HTML QUE OCUPARÁ A VARIÁVEL DE CONTEÚDO --}}
@section('conteudo')
    
<div class="conteudo-pagina">

    <div class="titulo-pagina-2">
        <p>Listagem de Clientes</p>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('cliente.create') }}">Novo</a></li>
            <li><a href="">Consulta</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">
        <div class="" style="width: 90%; margin-left: auto; margin-right: auto;">
            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clientes as $cliente)
                        <tr>
                            <td>{{ $cliente->nome }}</td>
                            <td><a href="{{ route('cliente.show', ['cliente' => $cliente->id]) }}">Visualizar</a></td>
                            <td>
                                <form id="form_{{$cliente->id}}" method="post" action="{{ route('cliente.destroy', ['cliente' => $cliente->id]) }}">
                                    @method('DELETE')
                                    @csrf
                                    {{-- <button type="submit">Excluir</button> --}}
                                    <a href="#" onclick="document.getElementById('form_{{$cliente->id}}').submit()">Excluir</a>
                                </form>
                            </td>
                            <td><a href="{{ route('cliente.edit', ['cliente' => $cliente->id]) }}">Editar</a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $clientes->appends($request)->links() }}
            <br>
            {{ $clientes->count() }} - clientes por página
            <br>
            {{ $clientes->total() }} - Total de registros da consulta   
            <br>
            {{ $clientes->firstItem() }} - Número do primeiro registro da página      
            <br>
            Exibindo {{ $clientes->count() }} clientes de {{ $clientes->total() }} (de {{ $clientes->firstItem() }} a {{ $clientes->lastItem() }})
    </div>

</div>

@endsection